"""Added some table

Revision ID: 2738ae232d1
Revises: None
Create Date: 2014-05-19 14:44:55.364206

"""

# revision identifiers, used by Alembic.
revision = '2738ae232d1'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.alter_column('page', 'description',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=2048),
               nullable=True)
    op.alter_column('page', 'site_url',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=2048),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page', 'site_url',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=2048),
               nullable=False)
    op.alter_column('page', 'description',
               existing_type=mysql.VARCHAR(collation='utf8_unicode_ci', length=2048),
               nullable=False)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8_unicode_ci', length=1024), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8_unicode_ci', length=1024), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8_unicode_ci', length=256), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8_unicode_ci', length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
