"""added column karma

Revision ID: 2d20a8abcdb
Revises: 4c72a141033
Create Date: 2014-05-25 18:06:46.475047

"""

# revision identifiers, used by Alembic.
revision = '2d20a8abcdb'
down_revision = '4c72a141033'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'page_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('comments', 'parent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('users', sa.Column('karma', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'karma')
    op.alter_column('comments', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('comments', 'parent_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('comments', 'page_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###
