"""added column Page(user_id, vote_up, vote_down, comments)

Revision ID: 37f499330a4
Revises: 2d20a8abcdb
Create Date: 2014-05-25 20:27:43.945491

"""

# revision identifiers, used by Alembic.
revision = '37f499330a4'
down_revision = '2d20a8abcdb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('vote_down', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('vote_up', sa.Integer(), nullable=True))
    op.add_column('pages', sa.Column('comments', sa.Integer(), nullable=True))
    op.add_column('pages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('pages', sa.Column('vote_down', sa.Integer(), nullable=True))
    op.add_column('pages', sa.Column('vote_up', sa.Integer(), nullable=True))
    op.drop_column('pages', 'down')
    op.drop_column('pages', 'up')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('up', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pages', sa.Column('down', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('pages', 'vote_up')
    op.drop_column('pages', 'vote_down')
    op.drop_column('pages', 'user_id')
    op.drop_column('pages', 'comments')
    op.drop_column('comments', 'vote_up')
    op.drop_column('comments', 'vote_down')
    ### end Alembic commands ###
