"""added column level in comments

Revision ID: 3dcf555e3a7
Revises: 194372eaa12
Create Date: 2014-05-26 00:23:29.219306

"""

# revision identifiers, used by Alembic.
revision = '3dcf555e3a7'
down_revision = '194372eaa12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('level', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'level')
    ### end Alembic commands ###
