"""Changer user.create_at to created_at

Revision ID: 4c72a141033
Revises: 5660b19bdce
Create Date: 2014-05-21 02:53:17.157769

"""

# revision identifiers, used by Alembic.
revision = '4c72a141033'
down_revision = '5660b19bdce'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'create_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_at', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'created_at')
    ### end Alembic commands ###
