"""Added index to comments.path

Revision ID: 55d46b38fa3
Revises: 3dcf555e3a7
Create Date: 2014-05-26 15:03:12.568267

"""

# revision identifiers, used by Alembic.
revision = '55d46b38fa3'
down_revision = '3dcf555e3a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_path'), 'comments', ['path'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_path'), table_name='comments')
    ### end Alembic commands ###
