"""Added switch users pk to id

Revision ID: 5660b19bdce
Revises: d435db6c61
Create Date: 2014-05-20 17:55:10.705570

"""

# revision identifiers, used by Alembic.
revision = '5660b19bdce'
down_revision = 'd435db6c61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
