"""added column default values=0 for some columns

Revision ID: 63374da944
Revises: 37f499330a4
Create Date: 2014-05-25 20:30:42.968824

"""

# revision identifiers, used by Alembic.
revision = '63374da944'
down_revision = '37f499330a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
