"""Added up/down column to table pages

Revision ID: 93cf643f24
Revises: 47295b463b3
Create Date: 2014-05-20 13:48:24.947886

"""

# revision identifiers, used by Alembic.
revision = '93cf643f24'
down_revision = '47295b463b3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page')
    op.add_column('pages', sa.Column('down', sa.Integer(), nullable=True))
    op.add_column('pages', sa.Column('up', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'up')
    op.drop_column('pages', 'down')
    op.create_table('page',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), nullable=False),
    sa.Column('site_title', mysql.VARCHAR(collation='utf8_unicode_ci', length=1024), nullable=True),
    sa.Column('site_url', mysql.VARCHAR(collation='utf8_unicode_ci', length=2048), nullable=True),
    sa.Column('description', mysql.VARCHAR(collation='utf8_unicode_ci', length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###
